---
- name: Ansible apt module example
# Defining the remote server where the package will be deployed 
  hosts: all
  remote_user: tmoore   # Using Remote user as ubuntu
  become: true
  tasks:

# Installing the zip, tree, and curl packages which are required to work with Apache server ( TASK-2) 
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - zip
        - tree

# Updating all packages to their latest version ( TASK-3) 

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

# Installing the curl package to test the Apache Server ( TASK-5) 
    - name: Update repositories cache and install "curl" package
      ansible.builtin.apt:
        name: curl
        update_cache: yes

