---
- name: Delete File(s)
# called with  --extra-vars  "nodes=base rmfilename=testme.txt"
  hosts: "{{ nodes }}"
  become: true
  vars:
    my_file: "{{ rmfilename }}"
  tasks:
    - name: Remove File
      file:
        path: "{{ my_file }}"
        state: absent

