---
- name: Delete File(s)
# called  ansible-playbook rm_file.yml --extra-vars "nodes=ansiblehosts rmfilename='/var/lib/dpkg/lock-frontend' "
  hosts: "{{ nodes }}"
  become: true
  vars:
    my_file: "{{ rmfilename }}"
  tasks:
    - name: Remove File
      file:
        path: "{{ my_file }}"
        state: absent

