---
  - name: Shell Examples
    hosts:  "{{ nodes }}"
    tasks:

    - name: Fix Logrotate daily compress
      ansible.builtin.shell:
         'sudo sed -i -e "s/weekly/daily/g" -e "s/^\tdelaycompress/\t#delaycompress/g" /etc/logrotate.d/rsyslog'
      register: sedcmd
      tags: sedcmd

#    - debug: msg="{{ sedcmd.stdout }}"
