---
  - name: Shell Examples
    hosts: "{{ nodes }}"
    tasks:

    - name: Check Date
      ansible.builtin.shell:
         "date"
      register: datecmd
      tags: datecmd

    - ansible.builtin.debug: msg="{{ datecmd.stdout }}"
